### ISSUE TITLE
Error generating PDF from format made with Print Designer

### ISSUE THREAD

**Issue by madco001** [frappe/print_designer#111] opened 2023-12-14 23:39 UTC
Hello, after creating my format in print designer, when I go to print I get the following error (ubuntu server 22.04):

Traceback (most recent call last):
File "apps/frappe/frappe/website/serve.py", line 18, in get_response
response = renderer_instance.render()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
html = self.get_html()
^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/utils.py", line 524, in cache_html_decorator
html = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
self.update_context()
File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
data = self.run_pymodule_method("get_context")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/website/page_renderers/template_page.py", line 225, in run_pymodule_method
return method(self.context)
^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/www/printview.py", line 57, in get_context
body = get_rendered_template(
^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/www/printview.py", line 212, in get_rendered_template
html = frappe.get_attr(hook_func[-1])(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/print_designer/print_designer/pdf.py", line 48, in pdf_body_html
return template.render(args, filters={"len": len})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "env/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "apps/print_designer/print_designer/print_designer/page/print_designer/jinja/main.html", line 178,
in top-level template code
{% set renderBody = render_element(bodyElement) %}
^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
return __context.call(__obj, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
rv = self._func(*arguments)
^^^^^^^^^^^^^^^^^^^^^^
File "apps/print_designer/print_designer/print_designer/page/print_designer/jinja/main.html", line 158,
in template
{{ render_element(object)}}
^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
return __context.call(__obj, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
rv = self._func(*arguments)
^^^^^^^^^^^^^^^^^^^^^^
File "apps/print_designer/print_designer/print_designer/page/print_designer/jinja/main.html", line 165,
in template
{{render_table(element)}}
File "env/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
return __context.call(__obj, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
rv = self._func(*arguments)
^^^^^^^^^^^^^^^^^^^^^^
File "apps/print_designer/print_designer/print_designer/page/print_designer/jinja/main.html", line 100,
in template
{% for row in doc.get(element.table.fieldname)%}
^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/runtime.py", line 417, in __init__
self._iterator = self._to_iterator(iterable)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "env/lib/python3.11/site-packages/jinja2/runtime.py", line 425, in _to_iterator
return iter(iterable)
^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

I deleted the table and it printed the PDF format, however it does not take the width of the sheet even though I have 0 in the margins.

![error0](https://github.com/frappe/print_designer/assets/118020503/a1c21c35-d56f-49eb-a740-a43ebaddb43c)

![error](https://github.com/frappe/print_designer/assets/118020503/32b74d39-9700-49c2-a557-313509e43629)

**wkhtmltopdf 0.12.6**

**Comment by maharshivpatel** [comment] 2023-12-15 04:50
@madco001 yes error is thrown when table is empty will fix this 😅

check first FAQ 
https://github.com/frappe/print_designer#faq
does your wkhtmtopdf version match ? patched qt is important

**Comment by maharshivpatel** [comment] 2023-12-16 04:01
@madco001 did you check wkhtmtopdf version to be qt patched as i shared earlier?

**Comment by aykun1907** [comment] 2023-12-16 04:50
I can confirm that it happens when the table is empty.  wkhtmltopdf 0.12.6. I came here to find out if there were any reporting's related to the issue and here there is.

**Comment by maharshivpatel** [comment] 2023-12-16 04:52
@aykun1907 that is known issue. you can just delete the table if not required. 

just select the table and press delete/backspace key.

**Comment by maharshivpatel** [comment] 2023-12-21 01:22
duplicate of #111 also pdf size issue is related to incorrect wkthtmltopdf version as shared earlier

**Closed by maharshivpatel** 2023-12-21 01:22 UTC
